
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 


alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Uncomment and modify if Alertmanager is ther
          # - "alertmanager:9093"


rule_files:
  # Uncomment and list any rule files
  # - "first_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "fastapi_instance1"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "fastapi_instance2"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8001"]